#!/bin/sh
# ============================================================================
# blocklists.sh - Global content filtering via dnsmasq blocklists
#
# Downloads and applies domain blocklists for gambling, porn, malware, etc.
# These are GLOBAL blocks (apply to all devices on the network).
# Lists are in dnsmasq format and loaded via conf-dir.
#
# Lists from: https://blocklistproject.github.io/Lists/
# Format: dnsmasq (server=/example.com/)
#
# Config file: /etc/config/parental_blocklists
# Format: one URL per line, # = comment
#
# Author: wighawag
# License: AGPL-3.0-only
# ============================================================================

set -u

CONFIG="${BLOCKLISTS_CONFIG:-/etc/config/parental_blocklists}"
BLOCKLIST_DIR="/tmp/dnsmasq-blocklists"
LOGGER="${LOGGER:-logger}"
WGET="${WGET:-wget}"
DNSMASQ_CONF="/etc/dnsmasq.d/blocklists.conf"

mkdir -p "$BLOCKLIST_DIR" 2>/dev/null || true

log() {
    $LOGGER -t parental-blocklists "$1" 2>/dev/null || echo "[parental-blocklists] $1" >&2
}

# Create default config if it doesn't exist
create_default_config() {
    if [ ! -f "$CONFIG" ]; then
        cat > "$CONFIG" << 'EOF'
# Global content filtering blocklists
# One URL per line. Lines starting with # are comments.
# Lists from https://blocklistproject.github.io/Lists/ (dnsmasq format)

# Gambling sites
https://blocklistproject.github.io/Lists/dnsmasq-version/gambling-dnsmasq.txt

# Porn / adult content
https://blocklistproject.github.io/Lists/dnsmasq-version/porn-dnsmasq.txt

# Malware
https://blocklistproject.github.io/Lists/dnsmasq-version/malware-dnsmasq.txt

# Phishing
https://blocklistproject.github.io/Lists/dnsmasq-version/phishing-dnsmasq.txt

# Ransomware
https://blocklistproject.github.io/Lists/dnsmasq-version/ransomware-dnsmasq.txt

# Scam
https://blocklistproject.github.io/Lists/dnsmasq-version/scam-dnsmasq.txt

# Fraud
https://blocklistproject.github.io/Lists/dnsmasq-version/fraud-dnsmasq.txt

# To add more categories, see https://blocklistproject.github.io/Lists/
# Available: ads, abuse, crypto, drugs, piracy, torrent, tracking, tiktok, etc.
EOF
        log "Created default config at $CONFIG"
    fi
}

# Download all blocklists
update_lists() {
    create_default_config

    local total=0
    local downloaded=0
    local failed=0

    echo "Downloading blocklists..."

    # Clear old lists
    rm -f "$BLOCKLIST_DIR"/*.txt 2>/dev/null

    while read -r url; do
        # Skip comments and empty lines
        case "$url" in
            \#*|"") continue ;;
        esac

        total=$((total + 1))
        local filename
        filename=$(echo "$url" | sed 's|.*/||; s|\.txt$||')
        local outfile="$BLOCKLIST_DIR/${filename}.txt"

        echo "  Downloading: $filename"
        if $WGET -q -O "$outfile" "$url" 2>/dev/null && [ -s "$outfile" ]; then
            local count
            count=$(wc -l < "$outfile")
            echo "    OK: $count domains"
            downloaded=$((downloaded + 1))
            total_domains=$((total_domains + count))
        else
            echo "    FAILED"
            failed=$((failed + 1))
            rm -f "$outfile" 2>/dev/null
        fi
    done < "$CONFIG"

    echo ""
    echo "Downloaded: $downloaded/$total lists ($failed failed)"

    if [ "$downloaded" -gt 0 ]; then
        configure_dnsmasq
        restart_dnsmasq
        log "Blocklists updated: $downloaded lists, $total_domains total domains blocked"
    fi

    return 0
}

# Configure dnsmasq to load blocklists from the directory
configure_dnsmasq() {
    # Create dnsmasq config snippet
    mkdir -p /etc/dnsmasq.d
    cat > "$DNSMASQ_CONF" << EOF
# Auto-generated by blocklists.sh
# Load blocklists from $BLOCKLIST_DIR
conf-dir=$BLOCKLIST_DIR,.txt
EOF

    # Make sure dnsmasq reads conf-dir (OpenWrt uses /etc/dnsmasq.d by default)
    # Add the conf-dir to the main dnsmasq config if not already there
    if ! uci get dhcp.@dnsmasq[0].confdir 2>/dev/null | grep -q "/etc/dnsmasq.d"; then
        uci set dhcp.@dnsmasq[0].confdir='/etc/dnsmasq.d'
        uci commit dhcp
    fi

    log "dnsmasq configured to load blocklists from $BLOCKLIST_DIR"
}

# Restart dnsmasq to apply changes
restart_dnsmasq() {
    /etc/init.d/dnsmasq restart 2>/dev/null || \
        rc-service dnsmasq restart 2>/dev/null || \
        killall -HUP dnsmasq 2>/dev/null
    log "dnsmasq restarted"
}

# Show status
show_status() {
    echo "Global Content Filtering Status"
    echo "==============================="
    echo ""

    if [ ! -f "$CONFIG" ]; then
        echo "Config file not found: $CONFIG"
        echo "Run: blocklists.sh update"
        return 0
    fi

    local configured=0
    while read -r url; do
        case "$url" in
            \#*|"") continue ;;
        esac
        configured=$((configured + 1))
    done < "$CONFIG"

    echo "Configured lists: $configured"
    echo ""

    local loaded=0
    local total_domains=0
    if [ -d "$BLOCKLIST_DIR" ]; then
        for f in "$BLOCKLIST_DIR"/*.txt; do
            [ -f "$f" ] || continue
            loaded=$((loaded + 1))
            local name
            name=$(basename "$f")
            local count
            count=$(wc -l < "$f")
            total_domains=$((total_domains + count))
            printf "  %-30s %s domains\n" "$name" "$count"
        done
    fi

    echo ""
    echo "Loaded lists: $loaded"
    echo "Total domains blocked: $total_domains"
    echo ""
    echo "Config file: $CONFIG"
    echo "Blocklist dir: $BLOCKLIST_DIR"
}

# List configured blocklists
list_configured() {
    echo "Configured blocklists:"
    if [ ! -f "$CONFIG" ]; then
        echo "  (no config at $CONFIG)"
        return 0
    fi
    while read -r url; do
        case "$url" in
            \#*|"") continue ;;
        esac
        local filename
        filename=$(echo "$url" | sed 's|.*/||')
        echo "  $filename"
        echo "    $url"
    done < "$CONFIG"
}

# Add a blocklist URL to the config
add_list() {
    local url="$1"
    if [ -z "$url" ]; then
        echo "Usage: blocklists.sh add <url>"
        return 1
    fi
    echo "$url" >> "$CONFIG"
    echo "Added: $url"
    echo "Run: blocklists.sh update  to download and apply"
}

# Remove a blocklist URL from the config
remove_list() {
    local url="$1"
    if [ -z "$url" ]; then
        echo "Usage: blocklists.sh remove <url>"
        return 1
    fi
    grep -v "^${url}$" "$CONFIG" > "$CONFIG.tmp" 2>/dev/null
    mv "$CONFIG.tmp" "$CONFIG"
    echo "Removed: $url"
    echo "Run: blocklists.sh update  to apply changes"
}

# Disable all blocklists (remove dnsmasq config)
disable() {
    rm -f "$DNSMASQ_CONF"
    restart_dnsmasq
    log "Blocklists disabled"
    echo "Blocklists disabled. Run: blocklists.sh update  to re-enable"
}

usage() {
    cat << EOF
Usage: blocklists.sh <command> [args]

Commands:
  update              Download all configured blocklists and apply
  status              Show current status (loaded lists, domain counts)
  list                List configured blocklist URLs
  add <url>           Add a blocklist URL to config
  remove <url>        Remove a blocklist URL from config
  disable             Disable all blocklists (keeps config, removes from dnsmasq)

Config: $CONFIG
Blocklists stored in: $BLOCKLIST_DIR (RAM, re-downloaded on update)

Default lists (auto-created on first update):
  gambling, porn, malware, phishing, ransomware, scam, fraud

More lists: https://blocklistproject.github.io/Lists/

Cron (weekly refresh):
  0 3 * * 0 /usr/bin/blocklists.sh update
EOF
}

case "${1:-}" in
    update)
        update_lists
        ;;
    status)
        show_status
        ;;
    list)
        list_configured
        ;;
    add)
        [ -z "${2:-}" ] && { echo "Error: missing URL" >&2; exit 1; }
        add_list "$2"
        ;;
    remove)
        [ -z "${2:-}" ] && { echo "Error: missing URL" >&2; exit 1; }
        remove_list "$2"
        ;;
    disable)
        disable
        ;;
    -h|--help|help|"")
        usage
        ;;
    *)
        echo "Unknown command: $1" >&2
        usage
        exit 1
        ;;
esac