#!/bin/sh
# ============================================================================
# setup-firewall.sh - Unknown device blocking via MAC allowlist
#
# Blocks all internet access for unknown (non-allowlisted) MAC addresses.
# This prevents children from bypassing parental controls by randomizing
# their MAC address.
#
# Config file: /etc/config/mac_allowlist (one MAC per line, # = comment)
# ============================================================================

set -eu

ALLOWLIST="${MAC_ALLOWLIST:-/etc/config/mac_allowlist}"
WAN_IF="${PARENTAL_WAN_IF:-$(uci get network.wan.device 2>/dev/null || echo "eth1")}"
LAN_IF="${PARENTAL_LAN_IF:-br-lan}"
IPTABLES="${IPTABLES:-iptables}"
FIREWALL_USER="${FIREWALL_USER:-/etc/firewall.user}"

# Generate the firewall.user file from the allowlist
generate_rules() {
    echo "# === PARENTAL CONTROL: BLOCK UNKNOWN DEVICES ==="
    echo "# Auto-generated by setup-firewall.sh"
    echo "# Allow known devices (insert at top -- these take priority)"
    echo ""

    if [ -f "$ALLOWLIST" ]; then
        while read -r mac comment; do
            # Skip comments and empty lines
            case "$mac" in
                \#*|"") continue ;;
            esac
            echo "iptables -I FORWARD 1 -i $LAN_IF -o $WAN_IF -m mac --mac-source $mac -j ACCEPT"
        done < "$ALLOWLIST"
    fi

    echo ""
    echo "# Block everything else from reaching the internet"
    echo "iptables -A FORWARD -i $LAN_IF -o $WAN_IF -j DROP"
}

# Apply rules immediately (in addition to writing firewall.user)
apply_now() {
    if [ -f "$ALLOWLIST" ]; then
        while read -r mac comment; do
            case "$mac" in
                \#*|"") continue ;;
            esac
            $IPTABLES -I FORWARD 1 -i "$LAN_IF" -o "$WAN_IF" -m mac --mac-source "$mac" -j ACCEPT 2>/dev/null || true
        done < "$ALLOWLIST"
    fi
    $IPTABLES -A FORWARD -i "$LAN_IF" -o "$WAN_IF" -j DROP 2>/dev/null || true
}

case "${1:-}" in
    generate)
        generate_rules
        ;;
    apply)
        generate_rules > "$FIREWALL_USER"
        apply_now
        echo "Firewall rules written to $FIREWALL_USER and applied"
        ;;
    write)
        generate_rules > "$FIREWALL_USER"
        echo "Firewall rules written to $FIREWALL_USER (not applied yet, will apply on firewall restart)"
        ;;
    -h|--help|help|"")
        echo "Usage: setup-firewall.sh <command>"
        echo ""
        echo "Commands:"
        echo "  generate    Print rules to stdout (dry run)"
        echo "  write       Write rules to $FIREWALL_USER (applies on reboot/firewall restart)"
        echo "  apply       Write rules AND apply immediately"
        ;;
    *)
        echo "Unknown command: $1" >&2
        exit 1
        ;;
esac