#!/bin/sh
# ============================================================================
# setup-firewall.sh - Unknown device blocking via nftables MAC allowlist
#
# Blocks all internet access for unknown (non-allowlisted) MAC addresses.
# Uses a dedicated nftables table separate from fw4.
#
# Config file: /etc/config/mac_allowlist (one MAC per line, # = comment)
#
# Author: wighawag
# License: AGPL-3.0-only
# ============================================================================

set -u

ALLOWLIST="${MAC_ALLOWLIST:-/etc/config/mac_allowlist}"
WAN_IF="${PARENTAL_WAN_IF:-$(uci get network.wan.device 2>/dev/null || echo "eth1")}"
LAN_IF="${PARENTAL_LAN_IF:-br-lan}"
NFT_BIN="${NFT:-nft}"
NFT_TABLE="parental_control"
NFT_ALLOWED_SET="allowed_macs"
LOGGER="${LOGGER:-logger}"

log() {
    $LOGGER -t parental "$1" 2>/dev/null || echo "[parental] $1" >&2
}

# Initialize the nftables table and sets
nft_init_allowlist() {
    # Create table if not exists
    $NFT_BIN list table inet "$NFT_TABLE" 2>/dev/null || \
        $NFT_BIN add table inet "$NFT_TABLE"

    # Create allowed_macs set if not exists
    $NFT_BIN list set inet "$NFT_TABLE" "$NFT_ALLOWED_SET" 2>/dev/null || \
        $NFT_BIN add set inet "$NFT_TABLE" "$NFT_ALLOWED_SET" '{ type ether_addr; }'

    # Remove old allow rules if they exist (we'll re-add them)
    # Flush the forward chain in our table
    $NFT_BIN flush chain inet "$NFT_TABLE" forward 2>/dev/null || \
        $NFT_BIN add chain inet "$NFT_TABLE" forward '{ type filter hook forward priority -10; policy accept; }'
}

# Generate nftables rules from the allowlist
generate_nft_rules() {
    echo "# === Parental Control: MAC Allowlist ==="
    echo "# Auto-generated by setup-firewall.sh"
    echo "# Only MACs in the allowed_macs set can access the internet."
    echo "# All other devices are blocked from LAN -> WAN forwarding."
    echo ""

    # Add each MAC to the allowed set
    if [ -f "$ALLOWLIST" ]; then
        while read -r mac comment; do
            case "$mac" in
                \#*|"") continue ;;
            esac
            echo "nft add element inet $NFT_TABLE $NFT_ALLOWED_SET { $mac }"
        done < "$ALLOWLIST"
    fi

    echo ""
    echo "# Allow known MACs to reach the internet"
    echo "nft add rule inet $NFT_TABLE forward iifname \"$LAN_IF\" oifname \"$WAN_IF\" ether saddr @$NFT_ALLOWED_SET accept"
    echo ""
    echo "# Block everything else from reaching the internet"
    echo "nft add rule inet $NFT_TABLE forward iifname \"$LAN_IF\" oifname \"$WAN_IF\" drop"
}

# Apply rules immediately using nftables
apply_nft() {
    nft_init_allowlist

    # Clear the allowed set
    $NFT_BIN flush set inet "$NFT_TABLE" "$NFT_ALLOWED_SET" 2>/dev/null

    # Add all allowed MACs to the set
    if [ -f "$ALLOWLIST" ]; then
        while read -r mac comment; do
            case "$mac" in
                \#*|"") continue ;;
            esac
            $NFT_BIN add element inet "$NFT_TABLE" "$NFT_ALLOWED_SET" "{ $mac }" 2>/dev/null
        done < "$ALLOWLIST"
    fi

    # Flush and recreate the forward chain rules
    $NFT_BIN flush chain inet "$NFT_TABLE" forward 2>/dev/null

    # Allow known MACs
    $NFT_BIN add rule inet "$NFT_TABLE" forward iifname "$LAN_IF" oifname "$WAN_IF" ether saddr @"$NFT_ALLOWED_SET" accept 2>/dev/null

    # Block everything else
    $NFT_BIN add rule inet "$NFT_TABLE" forward iifname "$LAN_IF" oifname "$WAN_IF" drop 2>/dev/null

    log "MAC allowlist applied via nftables"
}

# Generate an init script that runs on boot
generate_init_script() {
    cat << EOF
#!/bin/sh /etc/rc.common
# Auto-generated by setup-firewall.sh
# Applies the MAC allowlist on boot

START=99
USE_PROCD=1

start_service() {
    $(apply_nft | sed 's/\\/\\\\/g')
}

stop_service() {
    nft flush chain inet parental_control forward 2>/dev/null
}
EOF
}

case "${1:-}" in
    generate)
        generate_nft_rules
        ;;
    apply)
        apply_nft
        echo "MAC allowlist applied via nftables"
        echo "Allowed MACs:"
        $NFT_BIN list set inet "$NFT_TABLE" "$NFT_ALLOWED_SET" 2>/dev/null | grep -o '[0-9a-fA-F:]\{17\}' | while read -r mac; do
            echo "  $mac"
        done
        ;;
    init-script)
        generate_init_script > /etc/init.d/parental-allowlist
        chmod +x /etc/init.d/parental-allowlist
        /etc/init.d/parental-allowlist enable
        echo "Init script created and enabled at /etc/init.d/parental-allowlist"
        ;;
    -h|--help|help|"")
        echo "Usage: setup-firewall.sh <command>"
        echo ""
        echo "Commands:"
        echo "  generate      Print nftables rules to stdout (dry run)"
        echo "  apply         Apply rules immediately via nftables"
        echo "  init-script   Create and enable init script for boot-time application"
        echo ""
        echo "Config: $ALLOWLIST"
        echo "Table:  inet $NFT_TABLE"
        echo "Set:    $NFT_ALLOWED_SET"
        ;;
    *)
        echo "Unknown command: $1" >&2
        exit 1
        ;;
esac